=== gitpan/Lingua-Translit/xml/translit.dtd
<?xml version="1.0" encoding="UTF-8"?>


<!--

  Basic document type definition for transliteration tables.

  Copyright (C) 2007-2008 Alex Linke <alinke@lingua-systems.com>
  Copyright (C) 2009-2016 Lingua-Systems Software GmbH
  Copyright (C) 2016 Netzum Sorglos, Lingua-Systems Software GmbH

-->


<!ELEMENT translit  (name, desc, reverse, rules)>
<!ELEMENT name      (#PCDATA)>
<!ELEMENT desc      (#PCDATA)>
<!ELEMENT reverse   (#PCDATA)>
<!ELEMENT rules     (rule+)>
<!ELEMENT rule      (from, to, context?)>
<!ELEMENT from      (#PCDATA)>
<!ELEMENT to        (#PCDATA)>
<!ELEMENT context   ((before|after),(before|after)?)>
<!ELEMENT before    (#PCDATA)>
<!ELEMENT after     (#PCDATA)>


<!-- vim: set ft=dtd sts=4 ts=4 sw=4 ai et: -->

=== gitpan/Lingua-Translit/xml/iso_8859-16_ron.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE translit SYSTEM "translit.dtd">


<!--

  Transliteration definitions for Romanian diacritics.

  Copyright (C) 2015 È˜tefan Suciu <stefbv70@gmail.com>

-->


<translit>

    <name>ISO 8859-16 RON</name>
    <desc>Romanian with appropriate diacritics</desc>
    <reverse>true</reverse>

    <!-- set of transliteration rules -->
    <!--
    This transliteration is a simple mapping of characters with
    diacritics with cedilla below to the same character with diacritic
    using comma below in hex notation of Unicode codepoints
    (SR ISO/CEI 8859-16:2006 Latin10)
    (Letter names according to the Unicode Standard 5.0)
    Abbreviations:
    LCL = LATIN CAPITAL LETTER
    LSL = LATIN SMALL LETTER
    -->
    <rules>

        <rule>
            <from>&#x015E;</from>     <!-- LCL S WITH CEDILLA -->
            <to>&#x0218;</to>          <!-- LCL S WITH COMMA BELOW -->
        </rule>

        <rule>
            <from>&#x015F;</from>     <!-- LSL S WITH CEDILLA -->
            <to>&#x0219;</to>          <!-- LSL S WITH COMMA BELOW -->
        </rule>

        <rule>
            <from>&#x0162;</from>     <!-- LCL T WITH CEDILLA -->
            <to>&#x021A;</to>          <!-- LCL T WITH COMMA BELOW -->
        </rule>

        <rule>
            <from>&#x0163;</from>     <!-- LSL T WITH CEDILLA -->
            <to>&#x021B;</to>          <!-- LSL T WITH COMMA BELOW -->
        </rule>

    </rules>

</translit>

<!--
  vim: sts=4 sw=4 ai et
-->
